---
- name: "ipmi_exporter | Deploy ipmi_exporter modules"
  ansible.builtin.template:
    src: "ipmi_exporter.yml.j2"
    dest: "{{ vars['ipmi_exporter_dest'] + '/ipmi_exporter.yaml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Restart ipmi_exporter"
- name: "ipmi_exporter | Deploy ipmi_exporter service configuration"
  ansible.builtin.template:
    src: "ipmi_exporter.service.j2"
    dest: "{{ '/etc/systemd/system/' + vars['ipmi_exporter_service'] +
      '.service' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Daemon reload"
    - "Restart ipmi_exporter"
- name: "ipmi_exporter | Enable ipmi_exporter"
  ansible.builtin.systemd:
    name: "{{ vars['ipmi_exporter_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['ipmi_exporter'] is defined"
    - "hostvars[inventory_hostname]['ipmi_exporter'] != ''"
    - "hostvars[inventory_hostname]['ipmi_exporter'] |
       community.general.json_query(vars['ipmi_exporter_enable']) is defined"
    - "hostvars[inventory_hostname]['ipmi_exporter'] |
       community.general.json_query(vars['ipmi_exporter_enable']) == 'true'"
  vars:
    ipmi_exporter_enable: "[] | map(&enable || 'false', @) | [0]"
