---
- name: "ipmi_exporter | Download & unarchive exporter binary from tarball"
  ansible.builtin.unarchive:
    src: "{{ vars['ipmi_exporter_url'] + '/v' + vars['ipmi_exporter_version'] +
      '/ipmi_exporter-' + vars['ipmi_exporter_version'] + '.' +
      vars['ipmi_exporter_arch'] + '.tar.gz' }}"
    dest: "{{ vars['ipmi_exporter_dest'] }}"
    remote_src: "yes"
    include: "{{ 'ipmi_exporter-' + vars['ipmi_exporter_version'] + '.' +
      vars['ipmi_exporter_arch'] + '/ipmi_exporter' }}"
    mode: "0775"
    owner: "root"
    group: "root"
- name: "ipmi_exporter | Move exporter binary arfter unarchive"
  ansible.builtin.command:
    cmd: "{{ 'mv ' + vars['ipmi_exporter_dest'] + '/ipmi_exporter-' +
      vars['ipmi_exporter_version'] + '.' + vars['ipmi_exporter_arch'] +
      '/ipmi_exporter ' + vars['ipmi_exporter_dest'] + '/' }}"
    removes: "{{ vars['ipmi_exporter_dest'] + '/ipmi_exporter-' +
      vars['ipmi_exporter_version'] + '.' + vars['ipmi_exporter_arch'] +
      '/ipmi_exporter' }}"
- name: "ipmi_exporter | Deleting unnecessary directory"
  ansible.builtin.file:
    path: "{{ vars['ipmi_exporter_dest'] + '/ipmi_exporter-' +
      vars['ipmi_exporter_version'] + '.' + vars['ipmi_exporter_arch'] }}"
    state: "absent"
  diff: "false"
