---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.import_tasks:
    file: "download.yml"
- ansible.builtin.include_tasks:
    file: "deploy_ipmi_exporter.yml"
  when:
    - "vars['ipmi_exporter_settings'] is defined"
    - "vars['ipmi_exporter_settings'] != ''"
